name: Build Windows XP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install QEMU
      run: sudo apt-get install qemu

    - name: Create virtual disk
      run: qemu-img create -f qcow2 windows_xp.qcow2 10G

    - name: Start QEMU
      run: |
        qemu-system-x86_64 -accel kvm-hda windows_xp.qcow2 -cdrom path_to_windows_xp.iso -boot d -m 512 -vga std
