name: Run VM with VNC

on:
  push:
    branches:
      - main

jobs:
  run-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager
          sudo apt-get install -y xvfb x11vnc

      - name: Setup VM
        run: |
          mkdir -p ~/vm
          cd ~/vm
          # Örnek olarak bir Ubuntu ISO kullanıyoruz, kendi ISO'nuzu buraya yerleştirin
          wget https://releases.ubuntu.com/20.04/ubuntu-20.04.2.0-desktop-amd64.iso -O ubuntu.iso
          qemu-img create -f qcow2 ubuntu.qcow2 20G
          qemu-system-x86_64 -boot d -cdrom ubuntu.iso -m 2048 -hda ubuntu.qcow2 -vnc :1 &

      - name: Start VNC Server
        run: |
          export DISPLAY=:1
          Xvfb :1 -screen 0 1024x768x16 &
          x11vnc -display :1 -N -forever -shared &
